name: Zip Language Files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    # ✅ Define el entorno aquí, con el nombre exacto
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run zip script
        run: |
          chmod +x scripts/zip-lang.sh
          ./scripts/zip-lang.sh
          ls -la lang/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare Pages content
        run: |
          mkdir -p public
          cp -r lang/*.zip public/ || echo "No zip files found"
          touch public/.nojekyll
          echo "this is a custom domain" > public/auto.txt
          echo "=== Public directory structure ==="
          find public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
