name: Zip Language Files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment: # ¡CORRECCIÓN! Esto soluciona el error "Missing environment"
      name: github-pages # Especifica el entorno de Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run zip script
        run: |
          chmod +x scripts/zip-lang.sh
          ./scripts/zip-lang.sh

      - name: Prepare Pages content
        run: |
          mkdir -p public
          shopt -s nullglob 
          zip_files=(lang/*.zip)
          
          if [ ${#zip_files[@]} -gt 0 ]; then
            echo "Archivos zip encontrados: ${zip_files[@]}"
            mv "${zip_files[@]}" public/
          else
            echo "No se encontraron archivos zip en lang/."
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4