name: Zip Language Files

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run zip script
        run: |
          chmod +x scripts/zip-lang.sh
          ./scripts/zip-lang.sh
          echo "lang/ contents after zip:"
          ls -la lang/ || true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare Pages content (copy zips + generate index)
        run: |
          set -euo pipefail
          mkdir -p public
          shopt -s nullglob
          zips=(lang/*.zip)
          if [ ${#zips[@]} -eq 0 ]; then
            echo "No zip files found in lang/ — aborting deploy" >&2
            ls -la lang/ || true
            exit 1
          fi
          cp -v "${zips[@]}" public/
          # Option A: copy repo index.html if you want to keep your own page
          if [ -f index.html ]; then
            cp -v index.html public/index.html
          fi
          # Generate a simple index.html listing all zips (overwrites if present)
          {
            echo "<!doctype html>"
            echo "<meta charset='utf-8'>"
            echo "<title>Language zips</title>"
            echo "<h1>Language zips</h1>"
            echo "<ul>"
            for f in public/*.zip; do
              name=$(basename "$f")
              echo "  <li><a href=\"/$name\">$name</a> — <a href=\"/$name\" download>Download</a></li>"
            done
            echo "</ul>"
          } > public/index.html
          echo "public/ contents to deploy:"
          ls -la public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4