name: Zip Language Files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run zip script
        run: |
          chmod +x scripts/zip-lang.sh
          ./scripts/zip-lang.sh

      - name: Prepare Pages content
        run: |
          mkdir -p public
          if compgen -G "lang/*.zip" > /dev/null; then
            mv lang/*.zip public/
          else
            echo "No zip files found"
          fi

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: lang-zips
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
# ...existing code...